# time variant
name: 'time_mask'
# Specify paths to  data and results directory
data_directory:  /home/rabhi/dataset/temporal_hba1c/modelisation_hba1c_retino_v3/dictionaries/
validation_file_name:  "87_patients_min_10_seq_infos_Valid.sav"
train_file_name:  "689_patients_min_10_seq_infos_Train.sav"
test_file_name:  "86_patients_min_10_seq_infos_Test.sav"
min_measurement: 10
use_time_info: True
use_patient_info: True

result_dir: /home/rabhi/dataset/temporal_hba1c/results
side_info: ['duree_non_suivi_norm']

# Training info 
cycle_len: 25
batch_size: 20
val_bs: 87
device: cuda
n_workers: 4
class_weight: [0.45, 0.55]
max_len: 151

#optim info 
optimizer: sgd
weight_decay: 0.000006876
max_lr: 0.0005635
monitor: auc_score
mode: max

# patient module 
patient_config: 
  representation_type: mlp 
  num_inputs: 1
  hidden_dims: [4]
  activation: gelu
  output_dim: 56

# time module config 
time_config: 
  representation_type: time_mask
  hidden_dims: None
  projection_size: 24
  activation: 'gelu'
  output_dim: None
  embeddings_init_std: None
 
# event module config 
event_config: 
  categoricals: []
  continuous: ['seq_hba1c']
  categorical_representation: mlp
  continuous_representation: mlp
  categorical_embeddings: []
  continuous_hidden_dims: [24]
  continuous_output_dim: 56
  tf_activation: tanh

#model info 
aggregation_mode: mask-multiplication
model_type: attention
temporal_model: 
  input_size : None
  hidden_size : None
  dropout : None
  bidirectional : False 
  model_time : None
  timedecay_size : None
  num_layers : 1
  pad_value : -0.2
  attn_heads : None
  hidden_dropout_prob : 0.3
  feed_forward_hidden : 24
  hidden_act : relu
  attn_dropout_prob : 0.4
  num_input :  1
  output_self_attention : True
  use_position_embedding: True


# classification head
classifier:
  input_dim: None
  hidden_dim: 56
  output_dropout: 0.5
  num_classes: 2
  use_patient_info: None 
  patient_embedding_dim: None
