# time variant
name: 'time_encode'
# Specify paths to  data and results directory
data_directory:  /home/rabhi/dataset/temporal_hba1c/modelisation_hba1c_retino_v3/dictionaries/
validation_file_name:  "87_patients_min_10_seq_infos_Valid.sav"
train_file_name:  "689_patients_min_10_seq_infos_Train.sav"
test_file_name:  "86_patients_min_10_seq_infos_Test.sav"
min_measurement: 10 
use_time_info: False
use_patient_info: True

result_dir: /home/rabhi/dataset/temporal_hba1c/results
side_info: ['duree_non_suivi_norm']

# Training info 
cycle_len: 10
batch_size: 8
val_bs: 87
device: cuda
n_workers: 4
class_weight: [0.55, 0.45]
max_len: 151

#optim info 
optimizer: radam
weight_decay: 0.000005762
max_lr: 0.0002456
monitor: auc_score
mode: max

# patient module 
patient_config: 
  representation_type: mlp 
  num_inputs: 1
  hidden_dims: [28]
  activation: tanh
  output_dim: None

# time module config 
time_config: 
  representation_type: time_encode
  hidden_dims: None
  projection_size: None
  activation: 'gelu'
  output_dim: None
  embeddings_init_std: None
 
# event module config 
event_config: 
  categoricals: []
  continuous: ['seq_hba1c']
  categorical_representation: mlp
  continuous_representation: mlp
  categorical_embeddings: []
  continuous_hidden_dims: [28]
  continuous_output_dim: 16
  tf_activation: gelu

#model info 
aggregation_mode: element-wise-sum
model_type: attention
temporal_model: 
  input_size : None
  hidden_size : None
  dropout : None
  bidirectional : False 
  model_time : None
  timedecay_size : None
  num_layers : 8
  pad_value : -0.2
  attn_heads : None
  hidden_dropout_prob : 0.3
  feed_forward_hidden : 8
  hidden_act : tanh
  attn_dropout_prob : 0
  num_input :  1
  output_self_attention : True
  use_position_embedding: False


# classification head
classifier:
  input_dim: None
  hidden_dim: 64
  output_dropout: 0.2
  num_classes: 2
  use_patient_info: None 
  patient_embedding_dim: None
