# time variant
name: 'no_time'
# Specify paths to  data and results directory
data_directory:  /home/rabhi/dataset/temporal_hba1c/modelisation_hba1c_retino_v3/dictionaries/
validation_file_name:  "87_patients_min_10_seq_infos_Valid.sav"
train_file_name:  "689_patients_min_10_seq_infos_Train.sav"
test_file_name:  "86_patients_min_10_seq_infos_Test.sav"
min_measurement: 10
use_time_info: False
use_patient_info: True

result_dir: /home/rabhi/dataset/temporal_hba1c/results
side_info: ['duree_non_suivi_norm']

# Training info 
cycle_len: 30
batch_size: 24
val_bs: 87
device: cuda
n_workers: 4
class_weight: [0.7, 0.3]
max_len: 151

#optim info 
optimizer: adam
weight_decay: 0.00001838
max_lr: 0.0003554
monitor: auc_score
mode: max

# patient module 
patient_config: 
  representation_type: mlp 
  num_inputs: 1
  hidden_dims: [4]
  activation: relu
  output_dim: 56

# time module config 
time_config: 
  representation_type: identity
  hidden_dims: None
  projection_size: None
  activation: 'gelu'
  output_dim: 1
  embeddings_init_std: None
 
# event module config 
event_config: 
  categoricals: []
  continuous: ['seq_hba1c']
  categorical_representation: mlp
  continuous_representation: mlp
  categorical_embeddings: []
  continuous_hidden_dims: [28]
  continuous_output_dim: 40
  tf_activation: gelu

aggregation_mode: concat
model_type: lstm
temporal_model: 
  input_size : None
  hidden_size : 40
  dropout : 0.4
  bidirectional : True 
  model_time : None
  timedecay_size : None
  num_layers : 1
  pad_value : -0.2
  attn_heads : None
  hidden_dropout_prob : 0.3
  feed_forward_hidden : None
  hidden_act : tanh
  attn_dropout_prob : None
  num_input :  1
  output_self_attention : False

# classification head
classifier:
  input_dim: None
  hidden_dim: 64
  output_dropout: 0.5
  num_classes: 2
  use_patient_info: None 
  patient_embedding_dim: None
