# time variant
name: 'time_mask'
# Specify paths to  data and results directory
data_directory:  /home/rabhi/dataset/temporal_hba1c/modelisation_hba1c_retino_v3/dictionaries/
validation_file_name:  "87_patients_min_10_seq_infos_Valid.sav"
train_file_name:  "689_patients_min_10_seq_infos_Train.sav"
test_file_name:  "86_patients_min_10_seq_infos_Test.sav"
min_measurement: 10
use_time_info: True
use_patient_info: True

result_dir: /home/rabhi/dataset/temporal_hba1c/results
side_info: ['duree_non_suivi_norm']

# Training info 
cycle_len: 40
batch_size: 8
val_bs: 87
device: cuda
n_workers: 4
class_weight: [0.55, 0.45]
max_len: 151

#optim info 
optimizer: radam
weight_decay: 0.00009882
max_lr: 0.0001719
monitor: auc_score
mode: max

# patient module 
patient_config: 
  representation_type: mlp 
  num_inputs: 1
  hidden_dims: [28]
  activation: tanh
  output_dim: 24

# time module config 
time_config: 
  representation_type: time_mask
  hidden_dims: None
  projection_size: 20
  activation: 'gelu'
  output_dim: None
  embeddings_init_std: None
 
# event module config 
event_config: 
  categoricals: []
  continuous: ['seq_hba1c']
  categorical_representation: mlp
  continuous_representation: mlp
  categorical_embeddings: []
  continuous_hidden_dims: [20]
  continuous_output_dim: 40
  tf_activation: tanh

#model info 
aggregation_mode: mask-multiplication
model_type: lstm
temporal_model: 
  input_size : None
  hidden_size : 8
  dropout : 0.5
  bidirectional : True 
  model_time : None
  timedecay_size : None
  num_layers : 1
  pad_value : -0.2
  attn_heads : None
  hidden_dropout_prob : 0.5
  feed_forward_hidden : None
  hidden_act : tanh
  attn_dropout_prob : None
  num_input :  1
  output_self_attention : False

# classification head
classifier:
  input_dim: None
  hidden_dim: 48
  output_dropout: 0
  num_classes: 2
  use_patient_info: None 
  patient_embedding_dim: None
