# time variant
name: 'time_concat_soft'
# Specify paths to  data and results directory
data_directory:  /home/rabhi/dataset/temporal_hba1c/modelisation_hba1c_retino_v3/dictionaries/
validation_file_name:  "87_patients_min_10_seq_infos_Valid.sav"
train_file_name:  "689_patients_min_10_seq_infos_Train.sav"
test_file_name:  "86_patients_min_10_seq_infos_Test.sav"
min_measurement: 10
use_time_info: True
use_patient_info: True

result_dir: /home/rabhi/dataset/temporal_hba1c/results
side_info: ['duree_non_suivi_norm']

# Training info 
cycle_len: 30
batch_size: 24
val_bs: 87
device: cuda
n_workers: 4
class_weight: [0.6, 0.4]
max_len: 151

#optim info 
optimizer: radam
weight_decay: 0.00001383
max_lr: 0.003304
monitor: auc_score
mode: max

# patient module 
patient_config: 
  representation_type: mlp 
  num_inputs: 1
  hidden_dims: [24]
  activation: gelu
  output_dim: 40

# time module config 
time_config: 
  representation_type: soft-one-hot
  hidden_dims: None
  projection_size: 32
  activation: 'gelu'
  output_dim: 40
  embeddings_init_std: 0.98
 
# event module config 
event_config: 
  categoricals: []
  continuous: ['seq_hba1c']
  categorical_representation: mlp
  continuous_representation: mlp
  categorical_embeddings: []
  continuous_hidden_dims: [24]
  continuous_output_dim: 16
  tf_activation: tanh

#model info 
aggregation_mode: concat
model_type: lstm
temporal_model: 
  input_size : None
  hidden_size : 8
  dropout : 0.5
  bidirectional : True 
  model_time : None
  timedecay_size : None
  num_layers : 5
  pad_value : -0.2
  attn_heads : None
  hidden_dropout_prob : 0.1
  feed_forward_hidden : None
  hidden_act : gelu
  attn_dropout_prob : None
  num_input :  1
  output_self_attention : False

# classification head
classifier:
  input_dim: None
  hidden_dim: 16
  output_dropout: 0.2
  num_classes: 2
  use_patient_info: None 
  patient_embedding_dim: None
