# time variant
name: 'time_concat_soft'
# Specify paths to  data and results directory
data_directory:  /home/rabhi/dataset/temporal_hba1c/modelisation_hba1c_retino_v3/dictionaries/
validation_file_name:  "69_patients_min_15_seq_infos_Valid.sav"
train_file_name:  "552_patients_min_15_seq_infos_Train.sav"
test_file_name:  "69_patients_min_15_seq_infos_Test.sav"
min_measurement: 15
use_time_info: True
use_patient_info: True

result_dir: /home/rabhi/dataset/temporal_hba1c/results
side_info: ['duree_non_suivi_norm']

# Training info 
cycle_len: 35
batch_size: 24
val_bs: 69
device: cuda
n_workers: 4
class_weight: [0.65, 0.35]
max_len: 151

#optim info 
optimizer: adam
weight_decay: 0.00009768
max_lr: 0.000123
monitor: auc_score
mode: max

# patient module 
patient_config: 
  representation_type: mlp 
  num_inputs: 1
  hidden_dims: [16]
  activation: tanh
  output_dim: 8

# time module config 
time_config: 
  representation_type: soft-one-hot
  hidden_dims: None
  projection_size: 16
  activation: 'gelu'
  output_dim: 8
  embeddings_init_std: 0.2
 
# event module config 
event_config: 
  categoricals: []
  continuous: ['seq_hba1c']
  categorical_representation: mlp
  continuous_representation: mlp
  categorical_embeddings: []
  continuous_hidden_dims: [24]
  continuous_output_dim: 56
  tf_activation: relu

#model info 
aggregation_mode: concat
model_type: attention
temporal_model: 
  input_size : None
  hidden_size : None
  dropout : None
  bidirectional : False 
  model_time : None
  timedecay_size : None
  num_layers : 2
  pad_value : -0.2
  attn_heads : None
  hidden_dropout_prob : 0.1
  feed_forward_hidden : 40
  hidden_act : relu
  attn_dropout_prob : 0.4
  num_input :  1
  output_self_attention : True
  use_position_embedding: True


# classification head
classifier:
  input_dim: None
  hidden_dim: 48
  output_dropout: 0.1
  num_classes: 2
  use_patient_info: None 
  patient_embedding_dim: None
