# time variant
name: 'time_concat_soft'
# Specify paths to  data and results directory
data_directory:  /home/rabhi/dataset/temporal_hba1c/modelisation_hba1c_retino_v3/dictionaries/
validation_file_name:  "121_patients_min_3_seq_infos_Valid.sav"
train_file_name:  "965_patients_min_3_seq_infos_Train.sav"
test_file_name:  "121_patients_min_3_seq_infos_Test.sav"
min_measurement: 3
use_time_info: True
use_patient_info: True

result_dir: /home/rabhi/dataset/temporal_hba1c/results
side_info: ['duree_non_suivi_norm']

# Training info 
cycle_len: 15
batch_size: 4
val_bs: 121
device: cuda
n_workers: 4
class_weight: [0.45, 0.55]
max_len: 151

#optim info 
optimizer: radam
weight_decay: 0.00006623
max_lr: 0.0008929
monitor: auc_score
mode: max

# patient module 
patient_config: 
  representation_type: mlp 
  num_inputs: 1
  hidden_dims: [28]
  activation: gelu
  output_dim: 16

# time module config 
time_config: 
  representation_type: soft-one-hot
  hidden_dims: None
  projection_size: 24
  activation: 'gelu'
  output_dim: 16
  embeddings_init_std: 0.28
 
# event module config 
event_config: 
  categoricals: []
  continuous: ['seq_hba1c']
  categorical_representation: mlp
  continuous_representation: mlp
  categorical_embeddings: []
  continuous_hidden_dims: [20]
  continuous_output_dim: 56
  tf_activation: relu

#model info 
aggregation_mode: concat
model_type: lstm
temporal_model: 
  input_size : None
  hidden_size : 64
  dropout : 0.5
  bidirectional : True 
  model_time : None
  timedecay_size : None
  num_layers : 3
  pad_value : -0.2
  attn_heads : None
  hidden_dropout_prob : 0.1
  feed_forward_hidden : None
  hidden_act : relu
  num_input :  1
  output_self_attention : False

# classification head
classifier:
  input_dim: None
  hidden_dim: 64
  output_dropout: 0.5
  num_classes: 2
  use_patient_info: False 
  patient_embedding_dim: None
