# time variant
name: 'time_concat_mlp'
# Specify paths to  data and results directory
data_directory:  /home/rabhi/dataset/temporal_hba1c/modelisation_hba1c_retino_v3/dictionaries/
validation_file_name:  "69_patients_min_15_seq_infos_Valid.sav"
train_file_name:  "552_patients_min_15_seq_infos_Train.sav"
test_file_name:  "69_patients_min_15_seq_infos_Test.sav"
min_measurement: 15
use_time_info: True
use_patient_info: True

result_dir: /home/rabhi/dataset/temporal_hba1c/results
side_info: ['duree_non_suivi_norm']

# Training info 
cycle_len: 35
batch_size: 12
val_bs: 69
device: cuda
n_workers: 4
class_weight: [0.5, 0.5]
max_len: 151

#optim info 
optimizer: adam
weight_decay: 0.000009417
max_lr: 0.000154
monitor: auc_score
mode: max

# patient module 
patient_config: 
  representation_type: mlp 
  num_inputs: 1
  hidden_dims: [16]
  activation: tanh
  output_dim: 8

# time module config 
time_config: 
  representation_type: mlp
  hidden_dims: [16]
  projection_size: None
  activation: 'gelu'
  output_dim: 8
  embeddings_init_std: 0.8
 
# event module config 
event_config: 
  categoricals: []
  continuous: ['seq_hba1c']
  categorical_representation: mlp
  continuous_representation: mlp
  categorical_embeddings: []
  continuous_hidden_dims: [16]
  continuous_output_dim: 42
  tf_activation: relu

#model info 
aggregation_mode: concat
model_type: lstm
temporal_model: 
  input_size : None
  hidden_size : 56
  dropout : 0.5
  bidirectional : True 
  model_time : None
  timedecay_size : None
  num_layers : 3
  pad_value : -0.2
  attn_heads : None
  hidden_dropout_prob : 0.1
  feed_forward_hidden : None
  hidden_act : relu
  attn_dropout_prob : None
  num_input :  1
  output_self_attention : False

# classification head
classifier:
  input_dim: None
  hidden_dim: 40
  output_dropout: 0.1
  num_classes: 2
  use_patient_info: None 
  patient_embedding_dim: None
